module.exports = {
	EMPTY_TOKEN: 'token is empty',
	INVALID_TOKEN: 'token is invalid',
	MISSING_PARAMETERS: 'missing parameters',
	INVALID_EMAIL: 'invalid email',
	LOGIN_FAIL: 'login failed',
	LOGIN_SUCCESS: 'login success',
	REGISTER_SUCCESS: 'register success',
	ALREADY_EXIST_EMAIL: 'already exist email',
	ADD_CARD_FAIL: 'add card failed',
	ADD_CARD_SUCCESS: 'add card success',
	GET_MY_CARD_FAIL: 'get my card failed',
	GET_MY_CARD_SUCCESS: 'get my card success',
	DELETE_CARD_FAIL: 'delete card failed',
	DELETE_CARD_SUCCESS: 'delete card success',
	ADD_RELATION_FAIL: 'add relation failed',
	ADD_RELATION_SUCCESS: 'add relation success',
	ADD_MEMO_FAIL: 'add memo failed',
	ADD_MEMO_SUCCESS: 'add memo success',
	GET_MEMO_FAIL: 'get memo failed',
	GET_MEMO_SUCCESS: 'get memo success',
}